// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
	// Assets binding for serving static files
	ASSETS: Fetcher;
	
	// R2 bucket for storing PDF documents
	PDF_BUCKET: R2Bucket;
	
	// AI binding for Cloudflare Workers AI
	AI: {
		run<T>(model: string, inputs: unknown): Promise<T>;
		embeddings(model: string, text: string | string[]): Promise<number[][]>;
	};
	
	// Secrets
	MISTRAL_AI_API_KEY: string;
	JWT_SECRET: string;
}
