// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/documents": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/metadata-test": {
    params: {};
  };
  "/metadata-extract": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/documents" | "/chat" | "/metadata-test" | "/metadata-extract";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/documents.tsx": {
    id: "routes/documents";
    page: "/documents";
  };
  "routes/chat.tsx": {
    id: "routes/chat";
    page: "/chat";
  };
  "routes/metadata-test.tsx": {
    id: "routes/metadata-test";
    page: "/metadata-test";
  };
  "routes/metadata-extract.tsx": {
    id: "routes/metadata-extract";
    page: "/metadata-extract";
  };
};